version: '3' 
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - "127.0.0.1:5050:5050"
    environment:
      - PG_ADMIN_PORT=5050